using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CsvBlazor.Shared
{
    public class Columns : List<Column>
    {
        
    }
    public class Column
    {
        public Column(Guid guid)
        {
            this.Id = guid;
        }

        /// <summary>
        /// Autogenerated Guid
        /// </summary>
        public Guid Id { get; private set; }
        public string Name { get; set; }
        public string? MapTo { get; set; }

        public bool IsMapped => !string.IsNullOrEmpty(MapTo);
    }

    // Readed from DB
    public class ColumnDto
    {
        public string Name { get; set; }
        public string MapTo { get; set; }
    }
}
